# Generated by Django 6.0.2 on 2026-02-11 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(blank=True, max_length=255)),
                ('hero_subtitle', models.TextField(blank=True)),
                ('manifest_label', models.CharField(blank=True, help_text='Small label above the main manifest title (e.g. ARHIVA SCÂNTEIA)', max_length=255)),
                ('manifest_title', models.CharField(blank=True, max_length=255)),
                ('manifest_text', models.TextField(blank=True)),
                ('hero_bg_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
