# Generated by Django 6.0.2 on 2026-02-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpagecontent',
            name='hero_kicker',
            field=models.CharField(blank=True, help_text='Small line above the main title (e.g. CASA PRESEI LIBERE · BUCUREȘTI)', max_length=255),
        ),
    ]
