# Generated by Django 6.0.2 on 2026-02-12 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mainpagecontent_hero_kicker'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpagecontent',
            name='filosofie_cta_text',
            field=models.CharField(blank=True, default='SOLICITĂ O INVITAȚIE', max_length=255),
        ),
        migrations.AddField(
            model_name='mainpagecontent',
            name='filosofie_image_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='mainpagecontent',
            name='filosofie_intro',
            field=models.TextField(blank=True, default='Departe de agitația comercială, Ateliere la Scânteia oferă un\nspațiu unde timpul curge altfel.'),
        ),
        migrations.AddField(
            model_name='mainpagecontent',
            name='filosofie_label',
            field=models.CharField(blank=True, default='( FILOSOFIA NOASTRĂ )', max_length=255),
        ),
        migrations.AddField(
            model_name='mainpagecontent',
            name='filosofie_paragraph_1',
            field=models.TextField(blank=True, default='Într-un cerc restrâns și securizat, copiii scapă de presiunea\nnotelor și a performanței standardizate. Aici găsesc libertatea\nradicală de a crea fără frică.'),
        ),
        migrations.AddField(
            model_name='mainpagecontent',
            name='filosofie_paragraph_2',
            field=models.TextField(blank=True, default='Oferim materiale profesioniste și spațiu vital imens pentru ca\ncei mici să-și testeze limitele creativității într-un mediu sigur.'),
        ),
        migrations.AddField(
            model_name='mainpagecontent',
            name='filosofie_quote',
            field=models.TextField(blank=True, default='„Numărul strict limitat de locuri asigură că mentorul este un partener de dialog pentru fiecare copil, nu un supraveghetor.”'),
        ),
        migrations.AddField(
            model_name='mainpagecontent',
            name='filosofie_title_line_1',
            field=models.CharField(blank=True, default='Sanctuar Privat.', max_length=255),
        ),
        migrations.AddField(
            model_name='mainpagecontent',
            name='filosofie_title_line_2',
            field=models.CharField(blank=True, default='Libertate Radicală.', max_length=255),
        ),
        migrations.AddField(
            model_name='mainpagecontent',
            name='spatiul_image_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='mainpagecontent',
            name='spatiul_label',
            field=models.CharField(blank=True, default='( SPAȚIUL )', max_length=255),
        ),
        migrations.AddField(
            model_name='mainpagecontent',
            name='spatiul_paragraph',
            field=models.TextField(blank=True, default='Tavane înalte, lumină naturală de nord și o atmosferă care impune\nrespect pentru actul artistic. Spațiul nu e decor — este mentor.'),
        ),
        migrations.AddField(
            model_name='mainpagecontent',
            name='spatiul_quote',
            field=models.TextField(blank=True, default='„Numărul strict limitat de locuri asigură că mentorul este un partener de dialog pentru fiecare copil, nu un supraveghetor.”'),
        ),
        migrations.AddField(
            model_name='mainpagecontent',
            name='spatiul_stat_1_label',
            field=models.CharField(blank=True, default='MARMURĂ', max_length=64),
        ),
        migrations.AddField(
            model_name='mainpagecontent',
            name='spatiul_stat_1_value',
            field=models.CharField(blank=True, default='1956', max_length=32),
        ),
        migrations.AddField(
            model_name='mainpagecontent',
            name='spatiul_stat_2_label',
            field=models.CharField(blank=True, default='LUMINĂ NORD', max_length=64),
        ),
        migrations.AddField(
            model_name='mainpagecontent',
            name='spatiul_stat_2_value',
            field=models.CharField(blank=True, default='4m', max_length=32),
        ),
        migrations.AddField(
            model_name='mainpagecontent',
            name='spatiul_stat_3_label',
            field=models.CharField(blank=True, default='LINIȘTE', max_length=64),
        ),
        migrations.AddField(
            model_name='mainpagecontent',
            name='spatiul_stat_3_value',
            field=models.CharField(blank=True, default='∞', max_length=32),
        ),
        migrations.AddField(
            model_name='mainpagecontent',
            name='spatiul_title',
            field=models.CharField(blank=True, default='Suntem într-un monument.', max_length=255),
        ),
    ]
