# Generated by Django 6.0.2 on 2026-02-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_mainpagecontent_filosofie_cta_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpagecontent',
            name='hero_kicker',
            field=models.CharField(blank=True, default='CASA PRESEI LIBERE · BUCUREȘTI', help_text='Small line above the main title (e.g. CASA PRESEI LIBERE · BUCUREȘTI)', max_length=255),
        ),
        migrations.AlterField(
            model_name='mainpagecontent',
            name='hero_subtitle',
            field=models.TextField(blank=True, default='O enclavă de creație vizuală, unde copiii gândesc liber,\niar spațiul devine mentor.'),
        ),
        migrations.AlterField(
            model_name='mainpagecontent',
            name='hero_title',
            field=models.CharField(blank=True, default='Arta cere spațiu.\nȘi istorie.', max_length=255),
        ),
    ]
