# Generated by Django 6.0.2 on 2026-02-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_testimonial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonial',
        ),
        migrations.AddField(
            model_name='mainpagecontent',
            name='testimonial_1_name',
            field=models.CharField(blank=True, default='Ana M.', max_length=120),
        ),
        migrations.AddField(
            model_name='mainpagecontent',
            name='testimonial_1_quote',
            field=models.TextField(blank=True, default='Într-o lume a dopaminei instantanee, acesta este singurul loc unde fiul meu are răbdarea să lucreze două ore la o singură linie de cărbune.'),
        ),
        migrations.AddField(
            model_name='mainpagecontent',
            name='testimonial_1_role',
            field=models.CharField(blank=True, default='Partner @ Arhitectură & Design', max_length=255),
        ),
        migrations.AddField(
            model_name='mainpagecontent',
            name='testimonial_2_name',
            field=models.CharField(blank=True, default='Alexandru S.', max_length=120),
        ),
        migrations.AddField(
            model_name='mainpagecontent',
            name='testimonial_2_quote',
            field=models.TextField(blank=True, default='Scara monumentală a Casei Presei îi obligă pe copii să gândească mare. Nu există «drăgălășenii» aici. Există studiu, proporție și seriozitate.'),
        ),
        migrations.AddField(
            model_name='mainpagecontent',
            name='testimonial_2_role',
            field=models.CharField(blank=True, default='Tech Entrepreneur & Collector', max_length=255),
        ),
        migrations.AddField(
            model_name='mainpagecontent',
            name='testimonial_3_name',
            field=models.CharField(blank=True, default='Ioana D.', max_length=120),
        ),
        migrations.AddField(
            model_name='mainpagecontent',
            name='testimonial_3_quote',
            field=models.TextField(blank=True, default='Am căutat mult timp un loc care să nu fie un «parking de copii». Aici am găsit o comunitate de familii care împărtășesc aceleași valori.'),
        ),
        migrations.AddField(
            model_name='mainpagecontent',
            name='testimonial_3_role',
            field=models.CharField(blank=True, default='Medic & Membru Fondator', max_length=255),
        ),
        migrations.AddField(
            model_name='mainpagecontent',
            name='testimonial_4_name',
            field=models.CharField(blank=True, default='Maria T.', max_length=120),
        ),
        migrations.AddField(
            model_name='mainpagecontent',
            name='testimonial_4_quote',
            field=models.TextField(blank=True, default='Copiii mei au descoperit că arta nu este despre talent înnăscut, ci despre disciplină și observație atentă. Evoluția lor este incredibilă.'),
        ),
        migrations.AddField(
            model_name='mainpagecontent',
            name='testimonial_4_role',
            field=models.CharField(blank=True, default='Avocat & Colecționar', max_length=255),
        ),
        migrations.AddField(
            model_name='mainpagecontent',
            name='testimonial_5_name',
            field=models.CharField(blank=True, default='Cristian P.', max_length=120),
        ),
        migrations.AddField(
            model_name='mainpagecontent',
            name='testimonial_5_quote',
            field=models.TextField(blank=True, default='Spațiul în sine este o lecție de estetică. Fiecare dată când intrăm, copiii simt că fac parte din ceva care transcende simplul «curs de desen».'),
        ),
        migrations.AddField(
            model_name='mainpagecontent',
            name='testimonial_5_role',
            field=models.CharField(blank=True, default='Arhitect & Fondator Studio', max_length=255),
        ),
        migrations.AddField(
            model_name='mainpagecontent',
            name='testimoniale_title',
            field=models.CharField(blank=True, default='Vocile Comunității', max_length=255),
        ),
    ]
