# Generated by Django 6.0.2 on 2026-02-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_testimonial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpagecontent',
            name='manifest_card_1_text',
            field=models.TextField(blank=True, default='Discutăm cu părinții și înțelegem contextul copilului înainte de a confirma un loc.'),
        ),
        migrations.AddField(
            model_name='mainpagecontent',
            name='manifest_card_1_title',
            field=models.CharField(blank=True, default='Selecție atentă', max_length=255),
        ),
        migrations.AddField(
            model_name='mainpagecontent',
            name='manifest_card_2_text',
            field=models.TextField(blank=True, default='Menținem un grup mic pentru dialog real cu mentorul și progres vizibil.'),
        ),
        migrations.AddField(
            model_name='mainpagecontent',
            name='manifest_card_2_title',
            field=models.CharField(blank=True, default='Comunitate restrânsă', max_length=255),
        ),
        migrations.AddField(
            model_name='mainpagecontent',
            name='manifest_card_3_text',
            field=models.TextField(blank=True, default='Confirmarea se face prin invitație, în funcție de potrivirea cu valorile atelierelor.'),
        ),
        migrations.AddField(
            model_name='mainpagecontent',
            name='manifest_card_3_title',
            field=models.CharField(blank=True, default='Invitație, nu înscriere', max_length=255),
        ),
        migrations.AlterField(
            model_name='mainpagecontent',
            name='manifest_label',
            field=models.CharField(blank=True, default='( PROCESUL DE SELECȚIE )', help_text='Small label above the main manifest title (e.g. ARHIVA SCÂNTEIA)', max_length=255),
        ),
        migrations.AlterField(
            model_name='mainpagecontent',
            name='manifest_text',
            field=models.TextField(blank=True, default='Căutăm familii care înțeleg că educația estetică este o investiție pe viață.\nNu vindem cursuri. Construim fundații artistice.'),
        ),
        migrations.AlterField(
            model_name='mainpagecontent',
            name='manifest_title',
            field=models.CharField(blank=True, default='Accesul este limitat la\n12 membri pe sezon.', max_length=255),
        ),
    ]
