# Generated by Django 6.0.2 on 2026-02-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_mainpagecontent_manifest_card_1_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpagecontent',
            name='manifest_label',
            field=models.CharField(blank=True, default='( PROCESUL DE SELECȚIE )', help_text='Small label above the main manifest title (e.g. ( PROCESUL DE SELECȚIE ))', max_length=255),
        ),
    ]
