# Generated by Django 6.0.2 on 2026-02-12 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_mainpagecontent_manifest_label'),
        ('core', '0009_prefill_manifest_settings'),
    ]

    operations = [
    ]
