# Generated by Django 6.0.2 on 2026-02-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_jurnalindexpage_jurnalarticlepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpagecontent',
            name='spatiul_hidden_keywords',
            field=models.TextField(blank=True, default='', help_text='Opțional: keywords extra (separate prin virgulă sau pe linii). Poate fi afișat invizibil (sr-only) în frontend.'),
        ),
        migrations.AddField(
            model_name='mainpagecontent',
            name='spatiul_seo_blurb',
            field=models.TextField(blank=True, default='', help_text='Text scurt (1–2 fraze) pentru context SEO/geo. Recomandat să NU repete paragraful editorial.'),
        ),
    ]
