# Generated by Django 6.0.2 on 2026-02-14 15:07

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_mainpagecontent_spatiul_hidden_keywords_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='jurnalarticlepage',
            name='videos',
            field=wagtail.fields.StreamField([('video', 0)], blank=True, block_lookup={0: ('wagtail.blocks.URLBlock', (), {'help_text': 'YouTube/Vimeo/mp4 link', 'required': True})}),
        ),
        migrations.CreateModel(
            name='JurnalArticleGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, default='', max_length=140)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='core.jurnalarticlepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
