# Generated by Django 6.0.2 on 2026-02-21 11:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_jurnalarticlepage_videos_jurnalarticlegalleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('parent_name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('child_name', models.CharField(max_length=120)),
                ('child_age', models.CharField(max_length=20)),
                ('expectation', models.CharField(choices=[('hobby', 'Hobby'), ('performance', 'Performanță')], max_length=20)),
                ('source', models.CharField(blank=True, default='website', max_length=60)),
                ('art_relationship', models.TextField(blank=True, default='')),
                ('qa_json', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Aplicație Membrie',
                'verbose_name_plural': 'Aplicații Membrie',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MembershipQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Cheie unică (ex: art_relationship, expectation_note). Folosită în frontend/backend.', max_length=60, unique=True)),
                ('question_text', models.CharField(max_length=255)),
                ('suggested_answer', models.TextField(blank=True, default='')),
                ('required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Întrebare (Membrie)',
                'verbose_name_plural': 'Întrebări (Membrie)',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MembershipQAItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_items', to='core.membershipapplication')),
            ],
            options={
                'verbose_name': 'Q&A item',
                'verbose_name_plural': 'Q&A items',
                'ordering': ['order', 'id'],
            },
        ),
    ]
