# Generated by Django 6.0.2 on 2026-02-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_membershipapplication_membershipquestion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipquestion',
            name='suggested_answer',
            field=models.TextField(blank=True, default='', help_text='Placeholder / sugestie afișată în textarea (pre-filled ca hint).'),
        ),
    ]
