# Generated by Django 6.0.2 on 2026-02-21 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_membershipquestion_suggested_answer'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembrieFormContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_kicker', models.CharField(blank=True, default='( APLICAȚIE )', max_length=80)),
                ('form_title', models.CharField(blank=True, default='Solicită acces la\ncomunitatea noastră.', help_text='Titlul mare din formular (poți folosi \\n pentru line-break).', max_length=255)),
                ('form_title_emphasis', models.CharField(blank=True, default='comunitatea noastră', help_text='Cuvântul/fragmentul italic evidențiat (dacă îl folosești în frontend).', max_length=120)),
                ('loading_text', models.CharField(blank=True, default='Se încarcă formularul…', max_length=120)),
                ('step_label_template', models.CharField(blank=True, default='Pasul {step} din {total}', help_text='Template. Variabile: {step}, {total}.', max_length=120)),
                ('final_label', models.CharField(blank=True, default='Final', max_length=60)),
                ('back_button', models.CharField(blank=True, default='Înapoi', max_length=60)),
                ('continue_button', models.CharField(blank=True, default='Continuă', max_length=60)),
                ('submit_button', models.CharField(blank=True, default='Trimite candidatura', max_length=120)),
                ('submitting_button', models.CharField(blank=True, default='Se trimite…', max_length=120)),
                ('step1_title', models.CharField(blank=True, default='Detalii Părinte', max_length=120)),
                ('step1_subtitle', models.CharField(blank=True, default='Datele vor fi folosite doar pentru a te contacta.', max_length=255)),
                ('parent_name_label', models.CharField(blank=True, default='Nume complet', max_length=120)),
                ('parent_name_placeholder', models.CharField(blank=True, default='Numele și prenumele', max_length=255)),
                ('phone_label', models.CharField(blank=True, default='Telefon', max_length=120)),
                ('phone_placeholder', models.CharField(blank=True, default='+40 7XX XXX XXX', max_length=255)),
                ('email_label', models.CharField(blank=True, default='Email', max_length=120)),
                ('email_placeholder', models.CharField(blank=True, default='email@exemplu.ro', max_length=255)),
                ('step2_title', models.CharField(blank=True, default='Detalii Copil', max_length=120)),
                ('step2_subtitle', models.CharField(blank=True, default='Doar informațiile necesare pentru a înțelege profilul.', max_length=255)),
                ('child_name_label', models.CharField(blank=True, default='Numele copilului', max_length=120)),
                ('child_name_placeholder', models.CharField(blank=True, default='Numele copilului', max_length=255)),
                ('child_age_label', models.CharField(blank=True, default='Vârsta', max_length=120)),
                ('child_age_placeholder', models.CharField(blank=True, default='Selectează vârsta (minim 4 ani)', max_length=255)),
                ('step3_title_fallback', models.CharField(blank=True, default='Relația cu Arta', max_length=120)),
                ('step3_subtitle_fallback', models.CharField(blank=True, default='Descrieți, pe scurt, relația copilului cu arta până în prezent.', max_length=255)),
                ('step3_placeholder_fallback', models.CharField(blank=True, default='Ce medii artistice a explorat? Ce îl/o fascinează? Există lucrări de care este mândru/mândră?', max_length=255)),
                ('step3_min_chars_label', models.CharField(blank=True, default='Minim {min} caractere.', help_text='Template. Variabile: {min}.', max_length=120)),
                ('step4_title', models.CharField(blank=True, default='Așteptări', max_length=120)),
                ('step4_subtitle', models.CharField(blank=True, default='Ce căutați pentru copilul dumneavoastră?', max_length=255)),
                ('expectation_hobby_title', models.CharField(blank=True, default='Hobby', max_length=80)),
                ('expectation_hobby_desc', models.CharField(blank=True, default='Explorare creativă și dezvoltare personală', max_length=255)),
                ('expectation_performance_title', models.CharField(blank=True, default='Performanță', max_length=120)),
                ('expectation_performance_desc', models.CharField(blank=True, default='Pregătire pentru o carieră în arte vizuale', max_length=255)),
                ('success_title', models.CharField(blank=True, default='Aplicația a fost înregistrată.', max_length=255)),
                ('success_subtitle', models.CharField(blank=True, default='Comitetul de admitere vă va contacta în 48h.', max_length=255)),
                ('success_reset_button', models.CharField(blank=True, default='Trimite o nouă aplicație', max_length=120)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
