# Generated by Django 6.0.2 on 2026-02-21 13:00

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_membrieformcontent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membershipquestion',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Întrebare (Membrie) [legacy]', 'verbose_name_plural': 'Întrebări (Membrie) [legacy]'},
        ),
        migrations.RemoveField(
            model_name='membrieformcontent',
            name='form_title_emphasis',
        ),
        migrations.AddField(
            model_name='membrieformcontent',
            name='questions',
            field=wagtail.fields.StreamField([('question', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Cheie unică (ex: art_relationship). Doar litere mici, cifre și underscore.', 'max_length': 60, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Întrebare', 'max_length': 255, 'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'help_text': 'Text hint afișat în textarea.', 'label': 'Sugestie / placeholder', 'required': False}), 3: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'required': False}), 4: ('wagtail.blocks.IntegerBlock', (), {'default': 0, 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('key', 0), ('question_text', 1), ('suggested_answer', 2), ('required', 3), ('is_active', 3), ('order', 4)]], {})}),
        ),
        migrations.AlterField(
            model_name='membershipquestion',
            name='key',
            field=models.SlugField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='membershipquestion',
            name='suggested_answer',
            field=models.TextField(blank=True, default=''),
        ),
    ]
