# Generated by Django 6.0.2 on 2026-02-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_membershipquestion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipapplication',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='raw_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='user_agent',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='mainpagecontent',
            name='manifest_label',
            field=models.CharField(blank=True, default='( PROCESUL DE SELECȚIE )', help_text='Small line above the main manifest title (e.g. ( PROCESUL DE SELECȚIE ))', max_length=255),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
    ]
