# Generated by Django 6.0.2 on 2026-02-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_membershipapplication_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpagecontent',
            name='spatiul_stat_1_sublabel',
            field=models.CharField(blank=True, default='Nu 12, nu 15.', max_length=80),
        ),
        migrations.AddField(
            model_name='mainpagecontent',
            name='spatiul_stat_2_sublabel',
            field=models.CharField(blank=True, default='Percepția corectă a culorilor.', max_length=80),
        ),
        migrations.AddField(
            model_name='mainpagecontent',
            name='spatiul_stat_3_sublabel',
            field=models.CharField(blank=True, default='Competiție inutilă.', max_length=80),
        ),
        migrations.AlterField(
            model_name='mainpagecontent',
            name='filosofie_intro',
            field=models.TextField(blank=True, default='Răspundem direct celei mai stringente nevoi a părinților: atenția individuală.\nSpre deosebire de aglomerația din sistemul clasic, un mentor coordonează o grupă mică de maximum 4\ncopii.\nAcest raport asimetric garantează o educație personalizată, însă și un nivel de libertate\nesențial pentru cursuri de pictură și artă în București. Fiecare copil este ascultat, înțeles și\nîndrumat.'),
        ),
        migrations.AlterField(
            model_name='mainpagecontent',
            name='filosofie_paragraph_1',
            field=models.TextField(blank=True, default='Într-un cerc restrâns și securizat, copiii scapă de presiunea notelor și a performanței\nstandardizate. Aici găsesc libertatea radicală de a crea fără frică.'),
        ),
        migrations.AlterField(
            model_name='mainpagecontent',
            name='filosofie_paragraph_2',
            field=models.TextField(blank=True, default='Lucrăm cu materiale profesionale și spațiu vital imens pentru ca cei mici să își testeze limitele\ncreativității într-un mediu sigur.'),
        ),
        migrations.AlterField(
            model_name='mainpagecontent',
            name='filosofie_quote',
            field=models.TextField(blank=True, default='Numărul strict limitat de locuri asigură că mentorul este un partener de dialog pentru fiecare copil, nu un supraveghetor.', help_text='Textul din caseta peste imagine (secțiunea Filosofie).'),
        ),
        migrations.AlterField(
            model_name='mainpagecontent',
            name='filosofie_title_line_1',
            field=models.CharField(blank=True, default='Sanctuar privat.', max_length=255),
        ),
        migrations.AlterField(
            model_name='mainpagecontent',
            name='filosofie_title_line_2',
            field=models.CharField(blank=True, default='Libertate radicală.', max_length=255),
        ),
        migrations.AlterField(
            model_name='mainpagecontent',
            name='spatiul_paragraph',
            field=models.TextField(blank=True, default='Căutați un curs de pictură pentru copii în București unde atenția să nu se împartă la 15?\nAtelierele noastre de artă se desfășoară într-un spațiu diferit, ancorat în istoria orașului: clădirea\nmonumentală a Casei Presei Libere (fosta Casa Scânteii), în nordul Capitalei. Am înlocuit\naglomerația sălilor de clasă convenționale cu un mediu sigur, aerisit și lipsit de factori de stres,\nconceput pentru a stimula creativitatea.\nUnde și cum învață copilul tău? Locul este un instrument educațional în sine. Am transformat\nun studio generos într-un spațiu de concentrare, dedicat exclusiv micro-grupelor de doar 4\ncopii. Cu ferestre uriașe care inundă încăperea cu lumină naturală și o acustică ce elimină\nzgomotul de fond al orașului, mediul de lucru îi oferă copilului libertate de mișcare și liniștea\nnecesară pentru a explora arta.\nCopiii nu poartă nostalgia trecutului; ei sunt o formă pură de prezent. Pentru ei, acest\nmonument istoric nu este o relicvă, ci o pânză albă. Iar aici, educația vizuală devine un act de\nîncredere: încrederea că, într-un spațiu care a servit odată conformității, se pot naște acum cele\nmai libere idei.\nLocație monumentală. Siguranță absolută. Acolo unde educația de masă face compromisuri,\nAteliere la Scânteia livrează o garanție fermă: un mediu de învățare inspirațional, izolat de\nfactorii de stres, proiectat pentru dezvoltare creativă.'),
        ),
        migrations.AlterField(
            model_name='mainpagecontent',
            name='spatiul_quote',
            field=models.TextField(blank=True, default='Numărul strict limitat de locuri asigură că mentorul este un partener de dialog pentru fiecare copil, nu un supraveghetor.', help_text='Textul din caseta peste imagine.'),
        ),
        migrations.AlterField(
            model_name='mainpagecontent',
            name='spatiul_stat_1_label',
            field=models.CharField(blank=True, default='Copii într-o grupă.', max_length=64),
        ),
        migrations.AlterField(
            model_name='mainpagecontent',
            name='spatiul_stat_1_value',
            field=models.CharField(blank=True, default='4', max_length=32),
        ),
        migrations.AlterField(
            model_name='mainpagecontent',
            name='spatiul_stat_2_label',
            field=models.CharField(blank=True, default='Lumină naturală', max_length=64),
        ),
        migrations.AlterField(
            model_name='mainpagecontent',
            name='spatiul_stat_2_value',
            field=models.CharField(blank=True, default='100%', max_length=32),
        ),
        migrations.AlterField(
            model_name='mainpagecontent',
            name='spatiul_stat_3_label',
            field=models.CharField(blank=True, default='Zgomot. Presiune.', max_length=64),
        ),
        migrations.AlterField(
            model_name='mainpagecontent',
            name='spatiul_stat_3_value',
            field=models.CharField(blank=True, default='0', max_length=32),
        ),
        migrations.AlterField(
            model_name='mainpagecontent',
            name='spatiul_title',
            field=models.CharField(blank=True, default='Spațiul', max_length=255),
        ),
    ]
