# Generated by Django 6.0.2 on 2026-02-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_mainpagecontent_spatiul_stat_1_sublabel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpagecontent',
            name='filosofie_paragraph',
            field=models.TextField(blank=True, default='Răspundem direct celei mai stringente nevoi a părinților: atenția individuală.\nSpre deosebire de aglomerația din sistemul clasic, un mentor coordonează o grupă mică de maximum 4\ncopii.\nAcest raport asimetric garantează o educație personalizată, însă și un nivel de libertate\nesențial pentru cursuri de pictură și artă în București. Fiecare copil este ascultat, înțeles și\nîndrumat.\n\nÎntr-un cerc restrâns și securizat, copiii scapă de presiunea notelor și a performanței\nstandardizate. Aici găsesc libertatea radicală de a crea fără frică.\n\nLucrăm cu materiale profesionale și spațiu vital imens pentru ca cei mici să își testeze limitele\ncreativității într-un mediu sigur.', help_text='Un singur câmp pentru tot textul. Recomandat: separă blocurile cu o linie goală (Enter de 2 ori).'),
        ),
        migrations.AlterField(
            model_name='mainpagecontent',
            name='filosofie_intro',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='mainpagecontent',
            name='filosofie_paragraph_1',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='mainpagecontent',
            name='filosofie_paragraph_2',
            field=models.TextField(blank=True, default=''),
        ),
    ]
