# Generated by Django 6.0.2 on 2026-02-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_mainpagecontent_filosofie_paragraph_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpagecontent',
            name='manifest_card_1_text',
            field=models.TextField(blank=True, default='Arta nu se face sub neone și părinții caută un mediu de învățare sănătos, departe de lumina\nartificială a ecranelor. Spațiul nostru din Casa Presei oferă o iluminare naturală ideală, vitală\npentru percepția corectă a culorilor în artă. Acest aspect tehnic previne oboseala oculară și\nsusține concentrarea pe termen lung pe parcursul activităților educative de weekend.'),
        ),
        migrations.AlterField(
            model_name='mainpagecontent',
            name='manifest_card_1_title',
            field=models.CharField(blank=True, default='Lumina naturală', max_length=255),
        ),
        migrations.AlterField(
            model_name='mainpagecontent',
            name='manifest_card_2_text',
            field=models.TextField(blank=True, default='La Atelierele Scânteia, direcția educațională este asigurată de Andreea Apăvăloaei, absolventă\ncu nota 10 a Universitatea Nationala de Arte Bucuresti, cu un portofoliu impresionant consolidat\npe parcursul a trei decenii, orizontul ei artistic depășește cu mult șevaletul clasic. Abordând arta\nca pe o „meditație activă”, Andreea traduce pentru cursanții noștri o experiență multidisciplinară\ncomplexă și formare pedagogică acreditată (Certificare pedagogică DPPD).'),
        ),
        migrations.AlterField(
            model_name='mainpagecontent',
            name='manifest_card_2_title',
            field=models.CharField(blank=True, default='Mentoratul', max_length=255),
        ),
        migrations.AlterField(
            model_name='mainpagecontent',
            name='manifest_card_3_text',
            field=models.TextField(blank=True, default='Fără zgomot de fond, fără competiție inutilă pentru validarea profesorului. Acest volum aerian,\nspecific arhitecturii monumentale, previne suprastimularea senzorială unde copiii au libertatea\nde a se mișca'),
        ),
        migrations.AlterField(
            model_name='mainpagecontent',
            name='manifest_card_3_title',
            field=models.CharField(blank=True, default='Spațiu să creeze.\nLiniște să se concentreze.', max_length=255),
        ),
    ]
