# Generated by Django 6.0.2 on 2026-02-21 16:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_mainpagecontent_manifest_card_1_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('source', models.CharField(blank=True, default='website', max_length=60)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Abonat Newsletter',
                'verbose_name_plural': 'Abonați Newsletter',
                'ordering': ['-created_at'],
            },
        ),
    ]
