# Generated by Django 6.0.2 on 2026-02-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_newslettersubscriber_confirm_sent_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpagecontent',
            name='spatiul_paragraph',
            field=models.TextField(blank=True, default='Căutați un curs de pictură pentru copii în București unde atenția să nu se împartă la 15?\nAtelierele noastre de artă se desfășoară într-un spațiu diferit, ancorat în istoria orașului: clădirea\nmonumentală a Casei Presei Libere (fosta Casa Scânteii), în nordul Capitalei. Am înlocuit\naglomerația sălilor de clasă convenționale cu un mediu sigur, aerisit și lipsit de factori de stres,\nconceput pentru a stimula creativitatea.\nUnde și cum învață copilul tău? Locul este un instrument educațional în sine. Am transformat\nun studio generos într-un spațiu de concentrare, dedicat exclusiv micro-grupelor de doar 4\ncopii. Cu ferestre uriașe care inundă încăperea cu lumină naturală și o acustică ce elimină\nzgomotul de fond al orașului, mediul de lucru îi oferă copilului libertate de mișcare și liniștea\nnecesară pentru a explora arta.\nCopiii nu poartă nostalgia trecutului; ei sunt o formă pură de prezent. Pentru ei, acest\nmonument istoric nu este o relicvă, ci o pânză albă. Iar aici, educația vizuală devine un act de\nîncredere: încrederea că, într-un spațiu care a servit odată conformității, se pot naște acum cele\nmai libere idei.\n'),
        ),
    ]
