# Generated by Django 6.0.2 on 2026-02-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_mainpagecontent_spatiul_paragraph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpagecontent',
            name='manifest_text',
            field=models.TextField(blank=True, default='Ne adresăm familiilor care înțeleg că educația estetică se formează devreme și rămâne pentru totdeauna.\nCă sensibilitatea și discernământul vizual se cultivă în timp.\n\nNu oferim „activități creative” de weekend. Protejăm un loc în care copilul învață să privească înainte să judece, să aibă răbdare înainte să finalizeze și să aleagă înainte să copieze.\n\nȘi de cele mai multe ori, defapt, noi învățăm de la ei.'),
        ),
        migrations.AlterField(
            model_name='mainpagecontent',
            name='spatiul_stat_3_sublabel',
            field=models.CharField(blank=True, default='Fără competiție inutilă.', max_length=80),
        ),
    ]
