# base.py
"""
Django settings for ateliere_la_scanteia project.

Generated by 'django-admin startproject' using Django 6.0.2.
"""

from pathlib import Path
import os

PROJECT_DIR = Path(__file__).resolve().parent.parent
BASE_DIR = PROJECT_DIR.parent

# Load environment variables from a local .env file if present.
# We'll try multiple common locations to avoid path confusion in development.
try:
    from dotenv import load_dotenv

    for env_path in (
        BASE_DIR / ".env",          # repo root (one level above PROJECT_DIR)
        PROJECT_DIR / ".env",       # inside ateliere_la_scanteia folder
        Path.cwd() / ".env",        # where manage.py is executed from
    ):
        if env_path.exists():
            load_dotenv(env_path, override=True)
except Exception:
    pass


# ------------------------------------------------------------
# CORE SECURITY / ENV
# ------------------------------------------------------------

# Default to production-safe behavior unless explicitly set otherwise
DEBUG = os.getenv("DJANGO_DEBUG", "").strip() == "1"

# Use env var in production
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY") or os.getenv("SECRET_KEY") or "dev-insecure-secret-key-change-me"

# Public base URL (set this on Railway)
# Example: https://ateliere-la-scanteia-production.up.railway.app
PUBLIC_BASE_URL = (os.getenv("PUBLIC_BASE_URL") or "").strip().rstrip("/")

# Railway sometimes exposes a public domain env var; keep it optional
RAILWAY_PUBLIC_DOMAIN = (os.getenv("RAILWAY_PUBLIC_DOMAIN") or "").strip()

# Helper to extract host from a URL
def _host_from_url(url: str) -> str:
    if not url:
        return ""
    u = url.replace("https://", "").replace("http://", "")
    return u.split("/")[0].strip()


# Allowed hosts
ALLOWED_HOSTS = ["localhost", "127.0.0.1"]

if PUBLIC_BASE_URL:
    host = _host_from_url(PUBLIC_BASE_URL)
    if host:
        ALLOWED_HOSTS.append(host)

if RAILWAY_PUBLIC_DOMAIN:
    ALLOWED_HOSTS.append(RAILWAY_PUBLIC_DOMAIN)

# (Optional) keep known Railway URL as fallback
ALLOWED_HOSTS.append("ateliere-la-scanteia-production.up.railway.app")

# IMPORTANT for Railway / proxies: ensure Django knows requests are HTTPS
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# ------------------------------------------------------------
# APPLICATION DEFINITION
# ------------------------------------------------------------

INSTALLED_APPS = [
    "home",
    "search",
    "wagtail.contrib.forms",
    "wagtail.contrib.redirects",
    "wagtail.contrib.settings",
    "wagtail.embeds",
    "wagtail.sites",
    "wagtail.users",
    "wagtail.snippets",
    "wagtail.documents",
    "wagtail.images",
    "wagtail.search",
    "wagtail.admin",
    "wagtail",
    "modelcluster",
    "taggit",
    "django_filters",
    "rest_framework",
    "corsheaders",

    # Django contrib apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sitemaps",
    "django.contrib.postgres",  # ✅ REQUIRED for Postgres search fields / GinIndex

    "core",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "wagtail.contrib.redirects.middleware.RedirectMiddleware",
]

ROOT_URLCONF = "ateliere_la_scanteia.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            PROJECT_DIR / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "ateliere_la_scanteia.wsgi.application"


# ------------------------------------------------------------
# DATABASE
# ------------------------------------------------------------
# Railway Postgres provides DATABASE_URL.
# We ONLY use Postgres when DATABASE_URL is present.
# Otherwise we fall back to local SQLite.

DATABASE_URL = (os.getenv("DATABASE_URL") or "").strip()

if DATABASE_URL:
    import dj_database_url

    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
        )
    }

    # Require SSL in production by default (Railway managed Postgres supports it)
    if not DEBUG:
        DATABASES["default"].setdefault("OPTIONS", {})
        DATABASES["default"]["OPTIONS"].setdefault("sslmode", "require")
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# ------------------------------------------------------------
# PASSWORD VALIDATION
# ------------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# ------------------------------------------------------------
# INTERNATIONALIZATION
# ------------------------------------------------------------
LANGUAGE_CODE = "en-us"
TIME_ZONE = "Europe/Bucharest"
USE_I18N = True
USE_TZ = True


# ------------------------------------------------------------
# DJANGO REST FRAMEWORK
# ------------------------------------------------------------
REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": (
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ),
    "DEFAULT_PARSER_CLASSES": (
        "rest_framework.parsers.JSONParser",
        "rest_framework.parsers.FormParser",
        "rest_framework.parsers.MultiPartParser",
    ),
}


# ------------------------------------------------------------
# CORS
# ------------------------------------------------------------
# Dev defaults (you can override in dev.py with CORS_ALLOW_ALL_ORIGINS=True)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

# Allow your deployed frontend origin too (if you serve frontend elsewhere)
# If you serve frontend from same domain as backend, this is optional.
if PUBLIC_BASE_URL:
    CORS_ALLOWED_ORIGINS.append(PUBLIC_BASE_URL)


# ------------------------------------------------------------
# CSRF / ADMIN LOGIN FIX
# ------------------------------------------------------------
CSRF_TRUSTED_ORIGINS = []

if PUBLIC_BASE_URL.startswith("https://"):
    CSRF_TRUSTED_ORIGINS.append(PUBLIC_BASE_URL)

if RAILWAY_PUBLIC_DOMAIN:
    CSRF_TRUSTED_ORIGINS.append(f"https://{RAILWAY_PUBLIC_DOMAIN}")

CSRF_TRUSTED_ORIGINS.append("https://ateliere-la-scanteia-production.up.railway.app")

if not DEBUG:
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
else:
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SECURE = False


# ------------------------------------------------------------
# EMAIL (Membership applications)
# ------------------------------------------------------------
EMAIL_BACKEND = os.getenv("DJANGO_EMAIL_BACKEND", "").strip()
if not EMAIL_BACKEND:
    if os.getenv("DJANGO_EMAIL_HOST_USER") and os.getenv("DJANGO_EMAIL_HOST_PASSWORD"):
        EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    else:
        EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

DEFAULT_FROM_EMAIL = os.getenv("DJANGO_DEFAULT_FROM_EMAIL", "no-reply@cowicofi.eu")

EMAIL_HOST = os.getenv("DJANGO_EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.getenv("DJANGO_EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.getenv("DJANGO_EMAIL_USE_TLS", "1") == "1"
EMAIL_HOST_USER = os.getenv("DJANGO_EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("DJANGO_EMAIL_HOST_PASSWORD", "")
EMAIL_TIMEOUT = int(os.getenv("DJANGO_EMAIL_TIMEOUT", "20"))

MEMBRIE_APPLICATION_TO_EMAIL = os.getenv(
    "MEMBRIE_APPLICATION_TO_EMAIL",
    "iftim.florinn@gmail.com",
)


# ------------------------------------------------------------
# STATIC / MEDIA
# ------------------------------------------------------------
STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

STATICFILES_DIRS = [
    PROJECT_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "static"
STATIC_URL = "/static/"

MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"

STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {"BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"},
}

DATA_UPLOAD_MAX_NUMBER_FIELDS = 10_000


# ------------------------------------------------------------
# WAGTAIL
# ------------------------------------------------------------
WAGTAIL_SITE_NAME = "ateliere_la_scanteia"

WAGTAILSEARCH_BACKENDS = {
    "default": {
        "BACKEND": "wagtail.search.backends.database",
    }
}
# Keep SMTP in production; use console backend only in local DEBUG
if DEBUG and not (os.getenv("DJANGO_EMAIL_HOST_USER") and os.getenv("DJANGO_EMAIL_HOST_PASSWORD")):
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

NEWSLETTER_CONFIRM_TTL_HOURS = int(os.getenv("NEWSLETTER_CONFIRM_TTL_HOURS", "72"))

WAGTAILADMIN_BASE_URL = PUBLIC_BASE_URL or "http://localhost:8000"

WAGTAILDOCS_EXTENSIONS = [
    "csv", "docx", "key", "odt", "pdf", "pptx", "rtf", "txt", "xlsx", "zip"
]
